#!/usr/bin/env node

/**
 * Updates src/version.ts with the current version from package.json
 * This script is called automatically by npm during the version lifecycle
 */

const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const versionFilePath = path.join(__dirname, '..', 'src', 'version.ts');

// Read package.json
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

// Create version.ts content
const versionFileContent = `// This file is auto-generated by scripts/update-version.js during npm version
// Do not edit manually - it will be overwritten
export const version = '${version}';
`;

// Write to version.ts
fs.writeFileSync(versionFilePath, versionFileContent, 'utf8');

console.log(`Updated src/version.ts to version ${version}`);
